apiVersion: batch/v1
kind: Job
metadata:
  name: caf-client
  namespace: ping-pong
spec:
  completions: 2  # Set number of clients to run
  parallelism: 2  # Set number of clients to run
  template:
    metadata:
      labels:
        app: caf-client
    spec:
      restartPolicy: Never
      containers:
        - name: caf-client
          image: localhost:5001/ping-pong-lb-prime-client:v1
          args:
            - "--server-address=caf-load-balancer"
            - "--messages=20"
            - "--range=5000000"
            - "--verbose"
