apiVersion: batch/v1
kind: Job
metadata:
  name: caf-client
  namespace: ping-pong
spec:
  completions: 2  # Set number of clients to run
  parallelism: 2  # Set number of clients to run
  template:
    metadata:
      labels:
        app: caf-client
    spec:
      restartPolicy: Never
      containers:
        - name: caf-client
          image: localhost:5001/ping-pong-client:v4
          args:
            - "--server-address=caf-server"
            - "--messages=20"
            - "--delay=1000"
            - "--verbose"
